name: we_watch_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  adobe_xd: ^1.0.0+1
  dio: 2.0.11
  flutter_datetime_picker: ^1.2.8
  image_picker: ^0.6.7+3
  open_file: ^3.0.1
  flutter_svg: ^0.18.0
  video_trimmer: ^0.2.5
  fluttertoast: ^7.0.1
  shared_preferences: 0.5.7+3
  path_provider: ^1.6.11
  video_player: ^0.10.11+2
  provider: ^4.0.5
  wakelock: ^0.1.4+1
#  thumbnails: 1.0.1
  flick_video_player: ^0.1.1
  flutter_widgets: ^0.1.12
  chewie: ^0.9.10
  intl: ^0.16.1
  geolocator: ^5.3.2+2
  maps_launcher: ^1.2.0
  google_maps_flutter: ^0.5.28+1
  search_map_place: ^0.3.0
  flutter_google_places: ^0.2.6
  autocomplete_textfield: ^1.6.4
  toast: ^0.1.5
  share: ^0.6.3+4
  loadmore: ^1.0.4
  firebase_messaging: ^4.0.0+3
  device_preview: ^0.4.5
  slide_popup_dialog: ^0.0.2
  progress_dialog: ^1.2.4
  flutter_ffmpeg: ^0.2.10
  audio_recorder: ^1.0.2
  gallery_saver: ^2.0.1
  file_picker: ^1.7.0
  permission_handler: ^5.0.1+1
  geocoder: 0.2.1
  video_thumbnail : 0.2.2
#  google_maps_webservice: 0.0.18
  flutter_local_notifications: 2.0.0+1

  flutter_places_autocomplete: 0.2.0
  toggle_switch : 0.1.8
  font_awesome_flutter: 8.10.0




dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/splash.png
    - assets/images/logo_splash.png
    - assets/images/back_blue.png
    - assets/images/border_blue.png
    - assets/images/new.png
    - assets/images/fb_icon.png
    - assets/images/gmail_icon.png
    - assets/images/social.png
    - assets/images/india.png
    - assets/images/fitness.png
    - assets/images/entertainment.png
    - assets/images/image_one.png
    - assets/images/image_two.png
    - assets/images/image_three.png
    - assets/images/image_four.png
    - assets/images/image_five.png
    - assets/images/image_six.png
    - assets/images/bbbb.png
    - assets/images/three_dots.png
    - assets/images/live.png
    - assets/images/adventure.png
    - assets/images/desert.png
    - assets/images/comment_dp.png
    - assets/images/image_seven.png
    - assets/images/image_eight.png
    - assets/images/image_nine.png
    - assets/images/image_ten.png
    - assets/images/back_two.png
    - assets/images/profile_pic.png
    - assets/images/account.png
    - assets/images/help.png
    - assets/images/log_out.png
    - assets/images/outbox.png
    - assets/images/privacy_2.png
    - assets/images/setting.png
    - assets/images/stopwatch.png
    - assets/images/outbox_blue.png
    - assets/images/go_live.png
    - assets/images/car_img.png
    - assets/images/quarter_bg.png
    - assets/images/edit_blue.png
    - assets/images/image_twelve.png
    - assets/images/like_grey.png
    - assets/images/dislike_grey.png
    - assets/images/banner_one.png
    - assets/images/banner_two.png
    - assets/images/banner_three.png
    - assets/images/time.png
    - assets/images/category_sports.png
    - assets/images/category_food.png
    - assets/images/category_education.png
    - assets/images/category_fitness.png
    - assets/images/category_travel.png
    - assets/images/category_tech.png
    - assets/images/watch_list_grey.png
    - assets/images/share_grey.png
    - assets/images/subscribe_button.png
    - assets/images/camera_bg.png
    - assets/images/rotation.png
    - assets/images/timer.png
    - assets/images/cat_image_7.png
    - assets/images/cat_image_8.png
    - assets/images/cat_image_9.png
    - assets/images/cat_image_10.png
    - assets/images/cat_image_11.png
    - assets/images/cat_image_12.png
    - assets/images/social_worker_image.png
    - assets/images/image_profile.png
    - assets/images/worker.svg
    - assets/images/job.svg
    - assets/images/group.svg
    - assets/images/social_workers.svg
    - assets/images/tea.svg
    - assets/images/male.svg
    - assets/images/female.svg
    - assets/images/home_icon.svg
    - assets/images/play_icon.svg
    - assets/images/change_password.svg
    - assets/images/edit_personal.svg
    - assets/images/refresh.svg
    - assets/images/watch_later.svg
    - assets/images/add.svg
    - assets/images/my_videos.svg
    - assets/images/accessories.svg
    - assets/images/plant.svg
    - assets/images/spiritual.svg
    - assets/images/news_admin.svg
    - assets/images/cinema.svg
    - assets/images/music.svg
    - assets/images/password.svg
    - assets/images/confirm_password.svg
    - assets/images/email.svg
    - assets/images/calendar.svg
    - assets/images/city.svg
    - assets/images/state.svg
    - assets/images/zipcode.svg
    - assets/images/location.svg
    - assets/images/edit_profile_image.svg
    - assets/images/baseline_explore.svg
    - assets/images/edit_profile_image.png
    - assets/images/team.svg
    - assets/images/mind.svg
    - assets/images/group_two.svg
    - assets/images/real_estate.svg
    - assets/images/union.svg
    - assets/images/social_cause.svg
    - assets/images/heart.svg
    - assets/images/comment.svg
    - assets/images/tie.svg
    - assets/images/comments.png
    - assets/images/filter.png
    - assets/images/company_logo.png
    - assets/images/beats.png
    - assets/images/bookmark.svg
    - assets/images/share.svg
    - assets/images/share_white.svg
    - assets/images/bookmark_filled.svg
    - assets/images/startbucks.png
    - assets/images/camera.png
    - assets/images/gallery.png
    - assets/images/mylocation.png
    - assets/images/live_two.png
    - assets/images/empolyee_two.png
    - assets/images/jobs_feed_two.png
    - assets/images/latest_video_two.png
    - assets/images/social_workers_two.png
    - assets/images/play.png
    - assets/images/play_buttombar.png
    - assets/images/location.jpg



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
